/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
        System.out.println("Helo");
        //Rohtih
        System.out.println("Helo");
        System.out.println("Helo");
    }
}
